server:
  port: 8080
  tomcat:
    redirect-context-root:

spring:
  datasource:
          url: jdbc:mysql://127.0.0.1:3306/fpo?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 12345
          driver-class-name: com.mysql.jdbc.Driver
          platform: mysql
          type: com.alibaba.druid.pool.DruidDataSource
          # 下面为连接池的补充设置，应用到上面所有数据源中
          # 初始化大小，最小，最大
          initialSize: 1
          minIdle: 3
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 30000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,slf4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  #Redis 配置
  redis:
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器连接密码（默认为空）
    password: 12345
    pool:
      ## 连接池最大连接数（使用负值表示没有限制
      max-active: 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      ## 连接池中的最小空闲连接
      min-idle: 0
      ## 连接池中的最大空闲连接
      max-idle: 8
    ## 连接超时时间（毫秒）
    timeout: 0
  thymeleaf:
    mode: HTML5
    cache: false
  #RabbitMQ conifg
  rabbitmq:
    username: ppcg
    password: ppcg2018

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fpo.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#不用登录访问的URL
login.excludePaths: /favicon.ico, /login, /forgetPassword, /sendVerifyCode, /register, /front/*

#短信配置
smsConfig:
  accessKeyId: LTAIqIX23oyjqhD1
  accessKeySecret: tLOqqTjPnGa7TxHZczxjBL4Dd5x3iv
  signName: 人人采购

#oss配置
ossConfig:
  accessKeyId: LTAIqIX23oyjqhD1
  accessKeySecret: tLOqqTjPnGa7TxHZczxjBL4Dd5x3iv
  endpoint: oss-cn-shenzhen.aliyuncs.com
  publicBucket: ppcg-public2
  privateBucket: ppcg-private

#数据词典
dictConfig:
  invoiceModeMap:
    0: 不用发票
    1: 增值税普票
    2: 增值税专票
  quoteModeMap:
    1:  报价含税
    2:  报价含运费
  paymentModeMap:
    0: 其他
    1: 收货后付款
    2: 预付款
#日志配置
#logging:
#    file: /home/logs/log.log
#    pattern:
#      level: ERROR
